sudo: required
language: python
dist: xenial
cache: pip
python:
- '3.6'
- '3.7'
env:
  matrix:
  - TORCH_VER="1.5.0" TENSORFLOW_VER="1.15.0" secure: VVb1Gea4xkXqe5WbEdHvcCR1GC137eSu7VNoCrki9iF8Gxbbs0228rdTdI0Ob4o1X53ieTgMdZ1jZGVvqfDo0yIqiRqP1FXCCHu12NPyEL0pVZNMYbD8wJycOmX2hn3CX+LoKFvc76mR+qFAY0Q2Tq7JO2rt7mTCvhWc+fTWpUUoAPjqpofuxG+I5QGcitLTzZ+GobUhlAQbM778zHyT8+6Ouh9W/srAUjvs3hFVTu8g56BvLJ22GP4F4cMaUz3K7g+WJ/1yMnq9QDprdW4jPc4iUmPwhxiyKSdtU9witOeZBykxYCR+IzFSpBrejV+QlmCFkRWGQzzud+fe6QU71duXrZWmZNMTKrA+q+7hz42qpY/+221ObuK+caztdfPCJLJEdrOnvcgLG24Nw6+xb29xom7kjmCy9o06OzaYNT7nbkLDxH37U54pnmlP+tkWm4HS1bg+wj4CVlMbPFY0iieSbssPpz5GOwV4aD7HAi8iQQiX1nw1KUN0AFlQi5q9hb7MSdBZhVla16eBBmislC41A8qg/9vR6tiZ5UA9E6LY3D14uteMmrNRqJ8zIjXt1mTdhHgQNi/uA/kwJojoK7Hb1gp141wspeA1Y4oHEDBCpFjQTFyb7vH1MDfaPoSLvUZsz499sFApkJYk+LA3rHJh+jH0axCDw5ww2dWmFNk=
install:
- pip install --upgrade pip
- pip install --progress-bar off torch==$TORCH_VER
- pip install --progress-bar off tensorflow==$TENSORFLOW_VER
- pip install --progress-bar off .[nltk,ner,srl,txtgen,stanza,test,example,ir,wikipedia,spacy,sentiment,allennlp]
- git clone https://github.com/asyml/texar-pytorch.git
- cd texar-pytorch
- pip install --progress-bar off .
- cd ..
- rm -rf texar-pytorch
- wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.4.2-linux-x86_64.tar.gz
- tar -zxf elasticsearch-7.4.2-linux-x86_64.tar.gz
- rm -rf elasticsearch-7.4.2-linux-x86_64.tar.gz
- elasticsearch-7.4.2/bin/elasticsearch -d
- pip install faiss-cpu
- pip install pylint==2.5.2 flake8==3.8.2
- pip install mypy==0.780
- pip install pytest==5.1.3
- pip install coverage codecov
script:
- "./scripts/build_ontology_specs.sh"
- pylint forte/ examples/ ft/ scripts/ tests/
- flake8 forte/ examples/ ft/ scripts/ tests/
- mypy .
- spacy download en_core_web_sm
- spacy download xx_ent_wiki_sm
- python -m nltk.downloader punkt averaged_perceptron_tagger wordnet maxent_ne_chunker
  words
- export PYTHONPATH=`pwd`
- coverage run -m pytest
after_success:
- codecov
- "./scripts/travis_after_success.sh"
jobs:
  include:
  - stage: docs
    python: '3.7'
    install:
    - pip install --upgrade pip
    - pip install --progress-bar off -r requirements.txt
    - sudo apt-get install libenchant1c2a myspell-en-us
    - pip install --progress-bar off -r docs/requirements.txt
    - git clone https://github.com/asyml/texar-pytorch.git
    - cd texar-pytorch
    - pip install --progress-bar off .
    - cd ..
    - rm -rf texar-pytorch
    script:
    - cd docs
    - sphinx-build -W -b html -d _build/doctrees . _build/html
    - sphinx-build -b spelling -d _build/doctrees . _build/spelling
notifications:
  email: false
