sudo: required
language: python
dist: xenial
cache: pip
python:
- '3.6'
- '3.7'
env:
  global:
  - secure: upeWUFxPOAResmkc8UunXldkRAsAosgnzLtS+3I40VNM7NnSsYQHcCyI6iH77I4A+Ls5xShyf2AzFO/XNUAy7HltkmqdloG9di01bpLI0PuBb1aotGvCeF1qai/akRq+FKPs20RUhvxuw2f/Gw1/UgTCfXr04F0qK4rJkWz3vERzQb7I6LzlmmrhiQITAD/112ceqKBADW91SLWJCcy4Dka0AMDrgGLCrUw1Rxtl/F9VYl9AYc/2MEW6BS6TWjBKg5xuO4cVOViboS8q52wCFM70p5Ze6NrGEDr5t0gyZ/YHzsqUDuN/1KO5V7PBnTvi3wH5hqFe3yb7y4PFTe0EOLg9hyHckefpjuOjc6aFWHlZ7M9yqhAyE+sUpEwS7cHAgCc0vaoF0OjvtIIETdPa1LI5nhZf30ql+kkEya5SetYCFaWftPZ9fk72mJZwGrt9xi+MX3YrTjRb/VpysarcIdjNqGlxH5ZYXHpk0bWICcCZzZ/CQPW0Nlbpg550YrAB6VYmrKPCV4UgzvsTw4dARTZoDtGSg0mQsdLunONmyu2JvHVK+bwgfAZKZFus1SEvaS3tnkdPhjJVxmOYdWuoKT9B/CSWNI6pq5dlk7UU+OCYZE0zi+5ZSMRKRFTd6BQcOJ0s3MndnrzX3te1nI1wAKLA64l/nYdQuQ6tcLgdDEc=
  matrix:
  - TORCH_VER="1.5.0" TENSORFLOW_VER="1.15.0"
install:
- pip install --upgrade pip
- pip install --progress-bar off torch==$TORCH_VER
- pip install --progress-bar off tensorflow==$TENSORFLOW_VER
- pip install --progress-bar off .[nltk,ner,srl,txtgen,stanza,test,example,ir,wikipedia,spacy,sentiment,allennlp]
- git clone https://github.com/asyml/texar-pytorch.git
- cd texar-pytorch
- pip install --progress-bar off .
- cd ..
- rm -rf texar-pytorch
- wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.4.2-linux-x86_64.tar.gz
- tar -zxf elasticsearch-7.4.2-linux-x86_64.tar.gz
- rm -rf elasticsearch-7.4.2-linux-x86_64.tar.gz
- elasticsearch-7.4.2/bin/elasticsearch -d
- pip install faiss-cpu
- pip install pylint==2.5.2 flake8==3.8.2
- pip install mypy==0.780
- pip install pytest==5.1.3
- pip install coverage codecov
script:
- "./scripts/build_ontology_specs.sh"
- pylint forte/ examples/ ft/ scripts/ tests/
- flake8 forte/ examples/ ft/ scripts/ tests/
- mypy .
- spacy download en_core_web_sm
- spacy download xx_ent_wiki_sm
- python -m nltk.downloader punkt averaged_perceptron_tagger wordnet maxent_ne_chunker
  words
- export PYTHONPATH=`pwd`
- coverage run -m pytest
after_success:
- codecov
- "./scripts/travis_after_success.sh"
jobs:
  include:
  - stage: docs
    python: '3.7'
    install:
    - pip install --upgrade pip
    - pip install --progress-bar off -r requirements.txt
    - sudo apt-get install libenchant1c2a myspell-en-us
    - pip install --progress-bar off -r docs/requirements.txt
    - git clone https://github.com/asyml/texar-pytorch.git
    - cd texar-pytorch
    - pip install --progress-bar off .
    - cd ..
    - rm -rf texar-pytorch
    script:
    - cd docs
    - sphinx-build -W -b html -d _build/doctrees . _build/html
    - sphinx-build -b spelling -d _build/doctrees . _build/spelling
notifications:
  email: false
