# This provides a configuration for interence only

PipelineType: SinglePackPipeline
# Or maybe MultiPackTrainPipeline
Resources:
  # Instructions on how to build resources
  storage_path: "/home/shr/nlp_pipeline/examples/NER/resources.pkl"

GlobalConfig: null

DataInput:
  reader:
    type: CoNLL03Reader
    kwargs: null

globalconfig:

Processors:
  - type: "nlp.pipeline.processors.impl.tokenization_predictor.NLTKSentenceSegmenter"
    kwargs:
    configs:
  - type: "nlp.pipeline.processors.impl.tokenization_predictor.NLTKWordTokenizer"
    kwargs:
    configs:
  - type: "nlp.pipeline.processors.impl.postag_predictor.NLTKPOSTagger"
    kwargs:
    configs:
  - type: "nlp.pipeline.processors.impl.ner_predictor.CoNLLNERPredictor"
    kwargs:
    configs:
#  - type: SRLPredictor
# - type: this is not in a config+resource format

