# This provides a configuration for interence only

PipelineType: SinglePackPipeline
# Or maybe MultiPackTrainPipeline
Resources:
  # Instructions on how to build resources
  storage_path: "/home/shr/nlp_pipeline/examples/NER/resources.pkl"

GlobalConfig: null

DataInput:
  reader:
    type: CoNLL03Reader
    kwargs: null

globalconfig:

Processors:
  - type: VocularyProcessor
    kwargs: null
  - type: NERPredictor
    kwargs:
  - type: NLTKSentenceSegmenter
    kwargs:
  - type: NLTKWordTokenizer
    kwargs:
  - type: NLTKPOSTagger
    kwargs:
  - type: CoNLLNERPredictor
    kwargs:
#  - type: SRLPredictor
# - type: this is not in a config+resource format

