# This provides a configuration for interence only

# TODO: since we use pipeline.init_from_config(Hparams), we cannot set the PipelineType in the config
# Unless we have an external code parsing this configuratoin and create the Pipeline itself.

# PipelineType: SinglePackPipeline
# Or maybe MultiPackTrainPipeline

# Ontology:
Reader:
  type: CoNLL03Reader
  kwargs: null

Processors:
  - type: "nlp.pipeline.processors.impl.NLTKSentenceSegmenter"
  - type: "nlp.pipeline.processors.impl.NLTKWordTokenizer"
  - type: "nlp.pipeline.processors.impl.NLTKPOSTagger"
  - type: "nlp.pipeline.processors.impl.CoNLLNERPredictor"
    hparams:
      config_path: # Load config from the specified file if any
      overwrite_configs: # You can still define other configurations here
        storage_path: "/home/shr/nlp_pipeline/examples/NER/resources.pkl"
  - type: "nlp.pipeline.processors.impl.SRLPredictor"
    hparams:
      overwrite_configs:
        storage_path: "/home/hector/models/SRL_model/"